framework:
    messenger:
        failure_transport: failed

        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
             failed: 'doctrine://default?queue_name=failed'

        routing:
             'App\Domain\User\Action\Event\EventInterface': async

when@test:
    framework:
        messenger:
            transports:
                async: 'sync://'
